name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Setup .NET Core 5.0.x SDK'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore .NET dependencies
      run: dotnet restore
    - name: dotnet Build
      run: dotnet build --no-restore
    - name: dotnet Test
      run: dotnet test --no-build --verbosity normal
