name: 'Publish Nuget Package'

on:
  push:
    tags:
    - 'v*'
env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy Nuget Package'
    runs-on: windows-latest
    steps:
    - name: 'Chechout'
      uses: actions/checkout@v2

    - name: 'Install .NET Core 5 SDK'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: 'Restore .NET Dependences'
      run: dotnet restore

    - name: 'Execute dotnet build'
      run: dotnet build --no-restore --configuration Release

    - name: 'Execute dotnet test'
      run: dotnet test --no-build --verbosity normal

    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2
      
    - name: 'Pack Nuget Package'
      run: dotnet pack --no-restore --no-build --cofiguration Release  --output ${{ PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Publish Nuget Package'
      run: dotnet nuget push ${{ PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -s ${{ NUGET_SOURCE_URL }} --skip-duplicate -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --api-key ${{ secrets.NUGET_AUTH_TOKEN }}
