name: Release to Nuget

on:
  release:
    types: [published]

env:
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true'
  ARTIFACTS_DIRECTORY: ${{ github.workspace }}\artifacts
  PROJECT_PATH: ${{ github.workspace }}\src\Content\Net5WebTemplate.Api\Net5WebTemplate.Api.csproj

jobs:
  build:
    name: 'Build and Test Project'
    runs-on: windows-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: 'Install .NET Core 5 SDK'
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 5.0.x

     - name: 'Restore .NET Dependences'
       run: dotnet restore

     - name: 'Execute dotnet build'
       run: dotnet build --no-restore --configuration Release

     - name: 'Execute dotnet test'
       run: dotnet test --no-build --configuration Release --verbosity normal

     - name: 'Pack Project'
       run: dotnet pack ${{ env.PROJECT_PATH }} --no-build --no-restore --configuration Release -p:NuspecFile=${{ github.workspace }}\src\Content\Net5WebTemplate.nuspec -p:NuspecBasePath=${{ github.workspace }}\src\Content -p:NuspecProperties="version=${{ github.event.release.tag_name }}" -p:PackageVersion=${{ github.event.release.tag_name }} -p:PackageReleaseNotes="See https://github.com/marlonajgayle/Net5WebTemplate/releases/tag/${{ github.event.release.tag_name }}" --output ${{ env.ARTIFACTS_DIRECTORY }}

     - name: 'Archive Nuget Artifact'
       uses: actions/upload-artifact@v2.2.4
       with:
         name: packages
         path: ${{ env.ARTIFACTS_DIRECTORY }}

  push-github-packages:
    name: 'Push GitHub Packages'
    needs: [build]
    if: github.event_name == 'release'
    environment:
      name: 'GitHub Packages'
      url: https://github.com/marlonajgayle/Net5WebTemplate
    permissions:
      packages: write
    runs-on: windows-latest
    steps:
    - name: 'Download Artifact'
      uses: actions/download-artifact@v2
      with:
        name: 'packages'

    - name: 'Dotnet Nuget Add Source'
      run: dotnet nuget add source https://nuget.pkg.github.com/marlonajgayle/index.json --name github --username marlonajgayle --password ${{ secrets.WORKFLOW_AUTH_TOKEN }}

    - name: 'Dotnet Nuget Push'
      run: dotnet nuget push .\*.nupkg --api-key ${{ secrets.WORKFLOW_AUTH_TOKEN }} --source github --skip-duplicate