name: Release to Nuget

on:
  release:
    types: [published]

jobs:
  build:
    name: 'Build and Test Project'
    runs-on: windows-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: 'Install .NET Core 5 SDK'
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 5.0.x

     - name: 'Restore .NET Dependences'
       run: dotnet restore

     - name: 'Execute dotnet build'
       run: dotnet build --no-restore --configuration Release

     - name: 'Execute dotnet test'
       run: dotnet test --no-build --configuration Release --verbosity normal

     - name: 'Pack Project'
       run: dotnet pack -no-build --no-restore --configuration Release -p:PackageVersion=${{ github.event.release.tag_name }} -p:PackageReleaseNotes="See https://github.com/marlonajgayle/Net5WebTemplate/releases/tag/${{ github.event.release.tag_name }}"

     - name: 'Archive Nuget Artifact'
       uses: actions/upload-artifact@v2.2.4
       with:
         name: package
         path: '**/*.nupkg'